version: 2

sources:
  - name: raw_data 
    description: "Raw data sources for NYC taxi rides"
    database: dte-de-course-485814 #Project ID
    schema: nytaxi #Dataset name
    tables:
      - name: green_tripdata
      - name: yellow_tripdata